version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - kutahu-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kutahu
      MYSQL_USER: kutahu
      MYSQL_PASSWORD: kutahu
    
  kutahu:
    depends_on:
      - db
    build: .
    volumes:
      - kutahu-img-content:/var/www/html/Document
    ports:
      - "8000:80"
    restart: always
  
  phpma:
    image: beeyev/phpmyadmin-lightweight:latest
    depends_on:
      - db
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
volumes:
  kutahu-img-content: {}
  kutahu-db: {}

